import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Meme Showdown</title>
        <meta
          name="description"
          content="Meme showdown generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="bg-gradient-to-r from-purple-400 to-blue-400 h-screen text-white flex items-center justify-center">
          <a className="hover:text-pink-200" href="https://showdown.kpoppop.com">Welcome to the Showdown!</a>
        </p>
      </main>
    </div>
  );
};

export default Home;
